from youtube_transcript_api import YouTubeTranscriptApi

# retrieve the available transcripts
transcript_list = YouTubeTranscriptApi.list_transcripts('dQw4w9WgXcQ')

# iterate over all available transcripts
for transcript in transcript_list:

    # the Transcript object provides metadata properties
    print(
        transcript.video_id,
        transcript.video_language,
        transcript.language_code,
        # whether it has been manually created or generated by YouTube
        # check if translation is present - if not, let the user know
        transcript.is_generated,
        # whether this transcript can be translated or not
        transcript.is_translatable,
        # a list of languages the transcript can be translated to
        transcript.translation_languages,
    )

    transcript_data = transcript.fetch()
    transcript_string = ''

    # for the actual thing, add a regex filter so things like [Music] won't be included
    for line in transcript_data:
        transcript_string = transcript_string + line['text'] + ' '

    print(transcript_string)

    # fetch the actual transcript data
    print(transcript_data)

    # translating the transcript will return another transcript object
    print(transcript.translate('fr').fetch())

# # you can also directly filter for the language you are looking for, using the transcript list
# transcript = transcript_list.find_transcript(['de', 'en'])
#
# # or just filter for manually created transcripts
# # transcript = transcript_list.find_manually_created_transcript(['de', 'en'])
#
# # or automatically generated ones
# transcript = transcript_list.find_generated_transcript(['de', 'en'])
