"""
This type stub file was generated by pyright.
"""

from moviepy.decorators import requires_duration, use_clip_fps_by_default

"""MoviePy video GIFs writing."""
@requires_duration
@use_clip_fps_by_default
def write_gif_with_imageio(clip, filename, fps=..., loop=..., logger=...): # -> None:
    """Writes the gif with the Python library ImageIO (calls FreeImage)."""
    ...

