"""
This type stub file was generated by pyright.
"""

from dataclasses import dataclass
from moviepy.Effect import Effect

@dataclass
class BlackAndWhite(Effect):
    """Desaturates the picture, makes it black and white.
    Parameter RGB allows to set weights for the different color
    channels.
    If RBG is 'CRT_phosphor' a special set of values is used.
    preserve_luminosity maintains the sum of RGB to 1.
    """
    RGB: str = ...
    preserve_luminosity: bool = ...
    def apply(self, clip):
        """Apply the effect to the clip."""
        ...
    


