"""
This type stub file was generated by pyright.
"""

from dataclasses import dataclass
from moviepy.Clip import Clip
from moviepy.Effect import Effect

@dataclass
class LumContrast(Effect):
    """Luminosity-contrast correction of a clip."""
    lum: float = ...
    contrast: float = ...
    contrast_threshold: float = ...
    def apply(self, clip: Clip) -> Clip:
        """Apply the effect to the clip."""
        ...
    


