"""
This type stub file was generated by pyright.
"""

from dataclasses import dataclass
from moviepy.Clip import Clip
from moviepy.Effect import Effect

@dataclass
class MakeLoopable(Effect):
    """Makes the clip fade in progressively at its own end, this way it can be
    looped indefinitely.

    Parameters
    ----------

    overlap_duration : float
      Duration of the fade-in (in seconds).
    """
    overlap_duration: float
    def apply(self, clip: Clip) -> Clip:
        """Apply the effect to the clip."""
        ...
    


