"""
This type stub file was generated by pyright.
"""

from dataclasses import dataclass
from moviepy.Clip import Clip
from moviepy.Effect import Effect

@dataclass
class MaskColor(Effect):
    """Returns a new clip with a mask for transparency where the original
    clip is of the given color.

    You can also have a "progressive" mask by specifying a non-null distance
    threshold ``threshold``. In this case, if the distance between a pixel and
    the given color is d, the transparency will be

    d**stiffness / (threshold**stiffness + d**stiffness)

    which is 1 when d>>threshold and 0 for d<<threshold, the stiffness of the
    effect being parametrized by ``stiffness``
    """
    color: tuple = ...
    threshold: float = ...
    stiffness: float = ...
    def apply(self, clip: Clip) -> Clip:
        """Apply the effect to the clip."""
        ...
    


