"""
This type stub file was generated by pyright.
"""

from dataclasses import dataclass
from moviepy.Clip import Clip
from moviepy.Effect import Effect

@dataclass
class Painting(Effect):
    """Transforms any photo into some kind of painting.

    Transforms any photo into some kind of painting. Saturation
    tells at which point the colors of the result should be
    flashy. ``black`` gives the amount of black lines wanted.

    np_image : a numpy image
    """
    saturation: float = ...
    black: float = ...
    def to_painting(self, np_image, saturation=..., black=...): # -> ndarray[_AnyShape, dtype[Any]]:
        """Transforms any photo into some kind of painting.

        Transforms any photo into some kind of painting. Saturation
        tells at which point the colors of the result should be
        flashy. ``black`` gives the amount of black lines wanted.

        np_image : a numpy image
        """
        ...
    
    def apply(self, clip: Clip) -> Clip:
        """Apply the effect to the clip."""
        ...
    


